repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: lintr
        name: lintr
        entry: >-
          Rscript -e
          'files <- commandArgs(trailingOnly = TRUE);
          linters <- lintr::linters_with_defaults(
            object_usage_linter = NULL,
            object_name_linter = NULL,
            indentation_linter = NULL,
            line_length_linter = lintr::line_length_linter(100L)
          );
          lints <- unlist(
            lapply(files, lintr::lint, linters = linters),
            recursive = FALSE
          );
          print(lints);
          if (length(lints) > 0) quit(status = 1)'
        language: system
        files: "\\.(R|r)$"
