context('Real-world evidence tools')

test_that('cohort selection and matching work', {
  df <- data.frame(id = 1:4, age = c(50,60,70,80), treat = c(1,0,1,0), propensity = c(0.8,0.7,0.2,0.1))
  coh <- select_cohort(df, age > 55)
  expect_equal(nrow(coh), 3)
  mt <- match_cohort(df, caliper = 0.2)
  expect_true(nrow(mt) >= 0)
})

test_that('EHR analytics utilities operate', {
  ehr <- data.frame(patient_id = c(1,2), code = c('E110','A200'), value = c(5,3))
  std <- omop_standardize(ehr)
  expect_equal(names(std), c('person_id','concept_id','value'))
  notes <- c('Patient has diabetes', 'No issues noted')
  terms <- nlp_extract_concepts(notes)
  expect_true('patient' %in% terms$term)
  ph <- phenotype_diabetes(ehr)
  expect_true(any(ph))
  drug <- data.frame(patient_id=c(1,1,2), drug=c('a','a','b'), dose=c(1,2,3))
  exp <- drug_exposure_summary(drug)
  expect_equal(exp$dose[exp$patient_id==1],3)
})

test_that('regulatory helpers check frameworks', {
  report <- c('Safety','Efficacy','Population')
  expect_true(gvp_compliance(report))
  study <- list(data=1, analysis=2, submission=3)
  expect_true(fda_rwe_ready(study))
  pico <- ema_pico('pop','int','comp','out')
  expect_equal(pico$population,'pop')
  sections <- c(intro=TRUE, methods=TRUE)
  expect_true(strobe_compliant(sections))
})

test_that('data quality and outcomes work', {
  df <- data.frame(a=c(1,NA,3), b=c(NA,2,3))
  comp <- data_completeness(df)
  expect_equal(names(comp), c('a','b'))
  rules <- list(a=quote(a>0))
  val <- data_validate(df, rules)
  expect_equal(length(val),3)
  out <- detect_outliers_iqr(c(1,2,100))
  expect_equal(which(out),3)
  expect_true(temporal_consistency(as.Date('2020-01-01') + 0:2))
  expect_equal(analyze_prom(c(1,2,3)),2)
  expect_equal(quality_of_life_index(matrix(c(1,2,3,4),ncol=2))[1],1.5)
  mod <- hrqol_model(mpg~cyl, data=mtcars)
  expect_s3_class(mod,'lm')
  pref <- patient_preference(c('a','b','a'))
  expect_equal(pref$Freq[pref$options=='a'],2)
})
